config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :posts

  get '/posts' => redirect('/posts/show')
  post 'upvotes/:post_id', to: 'upvotes#create_upvote', as: 'upvote_button'
  post 'downvotes/:post_id', to: 'downvotes#create_downvote', as: 'downvote_button'

  resources :upvotes
  resources :downvotes

  root 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/downvote.rb
class Downvote < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  WillPaginate.per_page = 10
  belongs_to :user

  has_many :upvotes
  has_many :downvotes
  has_many :comments

  validates :title, presence: true

  def upvote
    upvotes.count + 1
  end

  def downvote
    downvotes.count + 1
  end

  def upvote_count
    upvotes.count
  end

  def downvote_count
    downvotes.count
  end

  def score
    upvotes.count - downvotes.count
  end

end

app/models/upvote.rb
class Upvote < ActiveRecord::Base
  belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts

  validates :username, presence: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.new
  end

  def show
    comment = find_comments_by_id

    if comment
      @comment = comment
    else
      render_not_found
    end
    redirect_to '/posts'
  end

  private

  def find_comments_by_id
    Comment.find(params[:post_id].to_i)
  end

end

app/controllers/downvotes_controller.rb
class DownvotesController < ApplicationController

  def index
    @downvote = Downvote.all
  end

  def create_downvote
    @downvote = Downvote.new
    @downvote.post = Post.find(params[:post_id])
    @downvote.save
    redirect_to :back
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    all_posts = Post.all.sort_by { |l| [l.score, l.title] }.reverse!

    current_page = params[:page].to_i

    if current_page <= 1
      start_number = 0
      end_number = 10
    else
      start_number = current_page + 10
      end_number = current_page * 10
    end

    @posts = all_posts[start_number..end_number]
  end

  def show
    post = Post.find(params[:id])
    if post
      @post = post
    else
      render_not_found
    end
  end

  def create
    Post.create(user_id: params[:post][:user_id],
                title: params[:post][:title],
                body: params[:post][:body])

    redirect_to '/posts'
  end

  private

  def render_not_found
    render template: 'posts/not_found.html.erb'
  end

end

app/controllers/upvotes_controller.rb
class UpvotesController < ApplicationController
  def index
    @upvote = Upvote.all
  end

  def create_upvote
    @upvote = Upvote.new
    @upvote.post = Post.find(params[:post_id])
    @upvote.save
    redirect_to :back
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    user = find_user_by_id

      if user
        @user = user
        @posts = @user.posts
      else
        render_not_found
      end
  end

  private

  def find_user_by_id
    User.find(params['id'].to_i)
  end

  def render_not_found
    render template: "/users/not_found.html.erb"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/downvotes_helper.rb
module DownvotesHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/upvotes_helper.rb
module UpvotesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/index.html.erb
<h1>Comments</h1>

<div class="comments">
  <ul>
    <% @comments.each do |t| %>
      <li><%= comment.message %></li> </br>
      <li><%= comment.author %></li>

        <a href="/posts/<%= comment.post_id %>">show</a>

    <% end %>
  </ul>
</div>

app/views/comments/new.html.erb
<div class="new_comment">
  <h1> Create a new comment!</h1>

  <form action="/comments" method="POST">
    <ul>
      <li>Comment <input type="text" name="message" id="message" /></li>
      <li>Author <input type="text" name="author" id="author" /><li>

      <input type="submit" name="commit" id="submit" />
    </ul>
  </form>
</div>

app/views/comments/show.html.erb
<div class="show_comment">
   <h2>Comment: <%= @comment.message %></h2>
   <h2>Author: <%= @comment.author %><h2>
    <form action="/comments/<%= @comment.comment_id %>/delete" method="POST">
      <input type="submit" name="Delete" id="submit" value="DELETE COMMENT" confirm=true/>

  <p>
    <a href="/comments">Go to All Comments</a>
  </p>

app/views/downvotes/create.html.erb
<h1>Downvote#create</h1>
<p>Find me in app/views/downvote/create.html.erb</p>

app/views/downvotes/destroy.html.erb
<h1>Downvote#destroy</h1>
<p>Find me in app/views/downvote/destroy.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Seentit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'shared/navigation' %>
    <div class="container">
      <div class="content">
        <%= yield %>
      </div>
    </div>

</body>
</html>

app/views/posts/index.html.erb
<p><a href="/posts/new"</a>Create New Post</p>

<div>

 <ul>
 <% @posts.each do |post| %>
  <li >
    <div class="post_box">
     <%= link_to post.title, post_path(post) %>
     <p> Posted by: <%= post.user.username %> </p>


      <div class="row post_box_bottom">
        <div class="vote_buttons">
          <%= button_to 'UpVote', upvote_button_path(post.id),  method: :post, class: 'button'%>
          <p class="scores">Total Votes: <%= post.score %></p>
          <%= button_to 'DownVote', downvote_button_path(post.id),  method: :post, class: 'button'%>
        </div>
      </div>
    </div>
   </li>
    <% end %>

</ul>
  <% if params[:page].to_i >= 0 %>
    <p><%= link_to "next page", "/posts?page=#{params[:page].to_i + 1}" %></p>
  <% end %>



  <% if params[:page].to_i > 1 %>
    <p><%= link_to "back page", "/posts?page=#{params[:page].to_i - 1}" %></p>
  <% end %>



</div>

app/views/posts/new.html.erb
<div class="form_Post">
  <%= render partial: 'shared/form' %>
</div>

app/views/posts/show.html.erb
<h4><%= @post.title %></h4>

  <h6>Posted by: <%= @post.user.username unless @post.user.blank? %></h6>
  <div class="post_body">
    <a><%= @post.body %></a>
  </div>

  <p><a href="/comments/new"</a>Create New Comment</p>

  <div class="comments">
    <h4><%= @post.comments.count %> Comments </h4>
    <% @post.comments.each do |comment| %>
      <p>Author: <%= comment.author %> </p>
      <p> <%= comment.comment %> </p>
    <% end %>
  </div>

</div>

app/views/shared/_form.html.erb
<div class='row'>
  <div class='twelve columns'>

    <% if @post && @post.errors %>
      <% @post.errors.full_messages.each do |msg| %>
        <p class='form-error'> <%= msg %> </p>
      <% end %>
    <% end %>

    <%= form_for Post.new do |l| %>
      <div class='row'>
        <div class='three columns'>
          <%= l.label :user_id %>
          <%= l.select :user_id, options_for_select(User.all.map { |user| [user.username, user.id] }), class: 'input-field user_id', placeholder: "Type here..." %>
        </div>
        <div class='three columns'>
          <%= l.label :title %>
          <%= l.text_field :title, class: 'input-field name', placeholder: "Title" %>
        </div>

        <div class='three columns'>
          <%= l.label :body %>
          <%= l.text_field :body, class: 'input-field body', placeholder: "Text" %>
        </div>


      </div>
      <div class='row'>
        <%= l.submit %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_navigation.html.erb
<header>

  <div class="row navigation">
    <div class="twelve columns navbar">
      <a class="navbar-brand" href="/users">Users</a>
      <a class="navbar-brand" href="/posts">Posts</a>
      <h1 class="site-title"> Seentit </h1>
      </div>
  </div>
</header>

app/views/upvotes/create.html.erb
<h1>Upvote#create</h1>
<p>Find me in app/views/upvote/create.html.erb</p>

app/views/upvotes/destroy.html.erb
<h1>Upvote#destroy</h1>
<p>Find me in app/views/upvote/destroy.html.erb</p>

app/views/users/index.html.erb
<h1>All Users</h1>

<div>
  <ol>
    <% @users.each do |user| %>
      <div class="user_box">
         <a href="/users/<%= user.id %>" > Show this user's posts</a>
         <p class="user_p"> Seentit User <%= user.username %> </p>
      </div>
    <% end %>
 </ol>
</div>

app/views/users/show.html.erb
<ul>

  <p>User: <%= @user.username unless @user.blank? %> </p>
    <% @posts.each do |post| %>
      <%= link_to post.title, post_path(post) %>
      <p></p>

    <% end %>


    </div>

      <p>
        <a href="/posts">Go to all posts</a>
      </p>

      <p>
        <a href="/users">Go to all users</a>
      </p>

</ul>